"""add verifier_notes column

Revision ID: 98844dc24da5
Revises: bde600ccaebb
Create Date: 2026-09-17 16:13:01.140387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98844dc24da5'
down_revision: Union[str, Sequence[str], None] = 'bde600ccaebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry_readings', sa.Column('verifier_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telemetry_readings', 'verifier_notes')
    # ### end Alembic commands ###
