"""create devices and telemetry_readings tables

Revision ID: bde600ccaebb
Revises: 
Create Date: 2026-09-17 16:12:33.931812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bde600ccaebb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vin', sa.String(), nullable=False),
    sa.Column('hashed_api_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_vin'), 'devices', ['vin'], unique=True)
    op.create_table('telemetry_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vin', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('battery_voltage', sa.Float(), nullable=False),
    sa.Column('state_of_charge', sa.Float(), nullable=False),
    sa.Column('kwh_consumed', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('flags', sa.String(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('e_base_kg', sa.Float(), nullable=False),
    sa.Column('e_project_kg', sa.Float(), nullable=False),
    sa.Column('e_avoided_kg', sa.Float(), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('chain_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_readings_vin'), 'telemetry_readings', ['vin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_readings_vin'), table_name='telemetry_readings')
    op.drop_table('telemetry_readings')
    op.drop_index(op.f('ix_devices_vin'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
